In [4]:
import pickle
from imblearn.over_sampling import SMOTE
import numpy as np

products = ['BANANAS', 'PEARLS']

In [22]:
a = np.array([[1,1,1,1,1,1],[2,2,2,2,2,2],[1,2,3,4,5,6]])
print(a)
a = np.transpose(a)
print(a)
a = a / np.linalg.norm(a, axis=1, keepdims=True)
print(a)
a = np.transpose(a)
print(a)

[[1 1 1 1 1 1]
 [2 2 2 2 2 2]
 [1 2 3 4 5 6]]
[[1 2 1]
 [1 2 2]
 [1 2 3]
 [1 2 4]
 [1 2 5]
 [1 2 6]]
[[0.40824829 0.81649658 0.40824829]
 [0.33333333 0.66666667 0.66666667]
 [0.26726124 0.53452248 0.80178373]
 [0.21821789 0.43643578 0.87287156]
 [0.18257419 0.36514837 0.91287093]
 [0.15617376 0.31234752 0.93704257]]
[[0.40824829 0.33333333 0.26726124 0.21821789 0.18257419 0.15617376]
 [0.81649658 0.66666667 0.53452248 0.43643578 0.36514837 0.31234752]
 [0.40824829 0.66666667 0.80178373 0.87287156 0.91287093 0.93704257]]


In [2]:
with open('trainingsets.pkl', 'rb') as f:
    trainingsets = pickle.load(f) # deserialize using load()

with open('traininggts.pkl', 'rb') as f:
    traininggts = pickle.load(f) # deserialize using load()

In [5]:
from src.logreg import LogisticRegression, serialize_logreg, deserialize_logreg

hardcode = {}
for product in products:
    hardcode[product] = []
    for i in range(9):
        logreg = LogisticRegression(num_iter=1000)
        sm = SMOTE(random_state=42)
        for (_, xss, _), (_, gts) in zip(trainingsets, traininggts):
            X_res, y_res = sm.fit_resample(xss[product], np.array(gts[product])[:,i])
            logreg.train(X_res, y_res)
        print(logreg.eval(X_res, y_res))
        hardcode[product].append(
            serialize_logreg(logreg)
        )
print(hardcode)

/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 9054]
 [   0 9054]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[ 126 9500]
 [   5 9621]]
0.5062850612923333


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9563    0]
 [9563    0]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 9345]
 [   0 9345]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9189    0]
 [9189    0]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 9544]
 [   0 9544]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[  56 9405]
 [   0 9461]]
0.5029595180213509


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9269    0]
 [9269    0]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[5058    0]
 [5058    0]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 9411]
 [   0 9411]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9799    0]
 [9799    0]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[  63 9868]
 [   0 9931]]
0.503171886013493


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9718  254]
 [9718  254]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 9423]
 [   0 9423]]
0.5


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[  63 9736]
 [   0 9799]]
0.5032146137360956


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[9831   92]
 [9424  499]]
0.5205079109140381


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[ 511 9456]
 [   0 9967]]
0.5256345941607304


/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))
/home/bhux/workplace/wat.ai/IMC-Prosperity/src/logreg.py:49: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-z))


[[   0 8232]
 [   0 8232]]
0.5
{'BANANAS': [{'learning_rate': 0.01, 'num_iter': 1000, 'fit_intercept': True, 'verbose': False, 'weights': [0.0024007545083358957, 12.23176475347374, 12.23176475347374, 12.23176475347374, 12.231764753475797, 0.0, 1.43020043721722, 1.4748363295199667, 1.4525183834899487, 1.4525208776319083, -0.031562342097655315, 7.359552831420725, 7.405427360130968, 7.419470482040946, 7.41947492494689, -0.005163638611775071, 8.03001193460534, 8.059494116409187, 8.038884387472365, 8.038884192740916, 0.019781195716811816, 21.798260174797925, 22.133828980449756, 21.943863191677334, 21.94387204030562, -0.04813949429494329, -1.1135411150956145, -0.4650383049589024, -0.6978068610677077, -0.6977740652216653, -0.1530718454405976, -50.02796841168356, -49.33670798379163, -49.678769834629, -49.678731852134796, -0.14940513556016302, 77.29434173044856, 78.03134976599229, 77.68433082715123, 77.68438841769712, -0.13070412608049448, 139.71856354086606, 140.63179592139468, 140.27694817082