In [1]:
import pickle
from imblearn.over_sampling import SMOTE
import numpy as np

products = ['BANANAS', 'PEARLS']

In [2]:
with open('trainingsets.pkl', 'rb') as f:
    trainingsets = pickle.load(f) # deserialize using load()

with open('traininggts.pkl', 'rb') as f:
    traininggts = pickle.load(f) # deserialize using load()

In [24]:
a = np.arange(12).reshape((3,-1))
print(a)
# a = np.transpose(a)
# print(a)
mean = np.mean(a, axis=0)
print(mean)
std = np.std(a, axis=0)
print(std)
a = (a - mean) / std
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[4. 5. 6. 7.]
[[-1.22474487 -1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487  1.22474487]]


In [25]:
from src.logreg import LogisticRegression, serialize_logreg, deserialize_logreg

hardcode = {}
for product in products:
    hardcode[product] = []
    for i in range(9):
        logreg = LogisticRegression(num_iter=1000)
        sm = SMOTE(random_state=42)
        for (_, xss, _), (_, gts) in zip(trainingsets, traininggts):
            X_res, y_res = sm.fit_resample(xss[product], np.array(gts[product])[:,i])
            logreg.train(X_res, y_res)
        print(logreg.eval(X_res, y_res))
        hardcode[product].append(
            serialize_logreg(logreg)
        )
print(hardcode)

ValueError: Input X contains NaN.
SMOTE does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values